app/blueprints/comment_bp.py
from app.db_interactors.comment_db_inter import CommentDbInter
from app.interactors.web_inter import WebInter

from flask import Blueprint, flash, redirect, render_template, request, url_for

from flask_login import login_required

comment_bp = Blueprint('comment_bp', __name__)


@comment_bp.route('/v1/drink/<drink_id>/comment', methods=['POST'])
@login_required
def add_comment(drink_id):
    """Add new comment.

    POST: Get comment data and add new Comment object to database.
          Flash confirmation and redirect to drink page. Only logged in users
          can use this route.

    Parameters
    ----------
    drink_id: int
    """
    if request.method == 'POST':
        d = WebInter().get_comment_data(drink_id)
        CommentDbInter().add_comment(author=d['author'],
                                     author_nick=d['author_nick'],
                                     drink=d['drink'],
                                     content=d['content'],
                                     date=d['date'])
        flash('Your comment has been added', category='success')
        return redirect(url_for('drink_bp.display_drink', drink_id=drink_id))


@comment_bp.route('/v1/drink/<drink_id>/comment/delete/<comment_id>',
                  methods=['GET'])
@login_required
def delete_comment(comment_id, drink_id):
    """Delete comment.

    GET: Route accepts comment_id as argument and deletes the Comment from
         database. Next it flash confirmation and redirect to drink page.
         Only logged in users can use this route.

    Parameters
    ----------
    comment_id: int
    drink_id: int
    """
    CommentDbInter().delete_comment(comment_id)
    flash('Comment has been deleted.', category='success')
    return redirect(url_for('drink_bp.display_drink', drink_id=drink_id))


@comment_bp.route('/v1/drink/<drink_id>/comment/edit/<comment_id>',
                  methods=['GET', 'POST'])
@login_required
def edit_comment(comment_id, drink_id):
    """Update comment.

        GET: Render template 'update_comment.html' allowing to edit comment
             body.
        POST: Update comment body and flash confirmation. Next redirects to
              drink page.
        Only logged in users can use this route.

        Parameters
        ----------
        comment_id: int
        drink_id: int
        """
    comment = CommentDbInter().get_comment(comment_id)
    if request.method == 'POST':
        CommentDbInter().update_comment(comment)
        flash('Your comment is updated.', category='success')
        return redirect(url_for('drink_bp.display_drink', drink_id=drink_id))
    else:
        return render_template('update_comment.html', title='Update comment',
                               comment=comment)

app/blueprints/drink_bp.py
from app.db_interactors.comment_db_inter import CommentDbInter
from app.db_interactors.drink_db_inter import DrinkDbInter
from app.db_interactors.ingredient_db_inter import IngredientDbInter
from app.db_interactors.search_db_inter import SearchDbInter
from app.db_interactors.user_db_inter import UserDbInter
from app.db_interactors.vote_db_inter import VoteDbInter
from app.interactors.img_inter import ImgInter
from app.interactors.web_inter import WebInter
from app.models import Drink

from flask import (Blueprint, flash, make_response, redirect,
                   render_template, request, url_for)

from flask_login import current_user, login_required

import werkzeug

drink_bp = Blueprint('drink_bp', __name__)


@drink_bp.route('/v1/add_drink', methods=['GET', 'POST'])
@login_required
def add_drink():
    """Add new drink.

    GET:  Render 'add_drink.html' template allowing introducing new drink
          properties.
    POST: Get drink data from HTML form and try to get image file of the drink.
          If there is no image it creates default image path and assign to
          Drink image property. Next it try to add new Drink object to database
          and if it is successful and image has been added by user it try to
          upload the image and update Drink image path. If it ends with success
          a confirmation is flashed and it redirects to new drink page.
          If any error occurs it flash the error and redirects to referrer page

    Only logged in users can use this route.
    """
    if request.method == 'GET':
        return render_template('add_drink.html', title='Add Drink',
                               categories=Drink.CATEGORIES,
                               techniques=Drink.TECHNIQUES)
    else:
        d = WebInter().get_drink_data()
        img = request.files['file']
        if img.filename == '':
            img_link = ImgInter().get_default_img('drink')
        else:
            img_link = None
        new_drink = Drink(name=d['name'].lower(),
                          category=d['category'],
                          technique=d['technique'],
                          author=d['author'],
                          author_nick=d['author_nick'],
                          description=d['description'],
                          preparation=d['preparation'],
                          add_date=d['add_date'],
                          image=img_link)
        try:
            DrinkDbInter().add_drink(new_drink, img)
            flash('Drink added successfully.', category='success')
            return redirect(url_for('drink_bp.display_drink',
                                    drink_id=new_drink.drink_id))
        except werkzeug.exceptions.BadRequest:
            flash('Incorrect file format. Please use .jpg .jpeg or .png',
                  category='error')
            return redirect(request.referrer)
        except werkzeug.exceptions.RequestEntityTooLarge:
            flash('The added file is too large. It should be < 1MB.',
                  category='error')
            return redirect(request.referrer)


@drink_bp.route('/v1/drink/<drink_id>', methods=['GET'])
def display_drink(drink_id):
    """Display drink page.

    GET: Render 'drink_page.html' template including all drink information.
         Also it increments Drink's views property.

    Parameters
    ---------
    drink_id: int
    """
    drink = DrinkDbInter().get_drink(drink_id)
    ingredients = IngredientDbInter().get_ingredients(drink_id)
    comments = CommentDbInter().get_drink_comments(drink_id)
    author = UserDbInter().get_user(drink.author).nick
    DrinkDbInter().views_counter(drink)
    return render_template('drink_page.html', title=drink.name.capitalize(),
                           drink=drink, ingredients=ingredients,
                           comments=comments, author=author)


@drink_bp.route('/v1/recommended', methods=['GET'])
def get_recommended():
    """Get top rated and most viewed drinks.

    GET: returns data of top rated and most viewed drinks.
    """
    try:
        top_rated_drink = DrinkDbInter().get_top_rated()
        most_viewed_drink = DrinkDbInter().get_most_viewed()
        return make_response({'success': True, 'top_rated': top_rated_drink,
                              'most_viewed': most_viewed_drink}, 200)
    except Exception:
        return make_response({'success': False,
                              'msg': 'Cannot get drinks.'}, 500)


@drink_bp.route('/v1/user_drinks/<user_id>/<int:page>')
@login_required
def user_drinks(user_id, page):
    """Display user's drinks.

    GET: Gets Pagination object of drinks assigned to the User. Next renders
         template 'user_drinks.html' including user's drinks for specific page.
         If there are not drinks it display information about that. Only logged
         in users can use this route.

    Parameters
    ---------
    user_id: int
    page: int
    """
    msg = 'Your Drinks:'
    drinks = SearchDbInter().search_by_user(user_id, page)
    if len(drinks.items) == 0:
        msg = 'You have not added drinks yet.'
    return render_template('user_drinks.html', title='Your Drinks',
                           drinks=drinks, msg=msg, user_id=user_id)


@drink_bp.route('/v1/drink/delete/<drink_id>', methods=['GET'])
@login_required
def delete_drink(drink_id):
    """Delete drink.

    GET: Delete Drink object and all Comment, Ingredient and Vote objects from
          database. If Drink image if different than default it is deleted from
          S3 bucket. In the end it flash confirmation and redirect to user's
          drinks page. Only logged in users can use this route.

    Parameters
    ---------
    drink_id: int
    """
    drink = DrinkDbInter().get_drink(drink_id)
    CommentDbInter().delete_many_comments(drink_id=drink_id)
    IngredientDbInter().delete_ingredients(drink_id)
    VoteDbInter().delete_drink_votes(drink_id)
    DrinkDbInter().delete_drink(drink_id)
    ImgInter().delete_img(drink)
    return redirect(url_for('drink_bp.user_drinks',
                            user_id=current_user.user_id,
                            page=1))


@drink_bp.route('/v1/drink/update/<drink_id>', methods=['GET', 'POST'])
@login_required
def update_drink(drink_id):
    """Update drink.

    GET: Render 'update_drink.html' template allowing editing current Drink
         properties.
    POST: Get drink data from HTML form and try to get image file of the drink.
          Updates drink data and if there is image passed by user it updates it
          in database and S3 bucket. If it ends with success a confirmation is
          flashed and it redirects to the drink page. If any error occurs it
          flash the error and redirects to referrer page.
    Only logged in users can use this route.

    Parameters
    ----------
    drink_id: int
    """
    drink = DrinkDbInter().get_drink(drink_id)
    old_ingr = IngredientDbInter().get_ingredients(drink_id)
    ingr_number = len(old_ingr)
    if request.method == 'POST':
        d = WebInter().get_drink_data()
        new_ingr = WebInter().get_ingredients()
        img = request.files['file']
        try:
            DrinkDbInter().update_drink(drink=drink,
                                        name=d['name'],
                                        category=d['category'],
                                        technique=d['technique'],
                                        description=d['description'],
                                        preparation=d['preparation'],
                                        img=img)
            IngredientDbInter().update_ingredients(drink, new_ingr)
            flash('Drink data has been updated.', category='success')
            return redirect(url_for('drink_bp.display_drink',
                                    drink_id=drink_id))
        except werkzeug.exceptions.BadRequest:
            flash('Incorrect file format. Please use .jpg .jpeg or .png',
                  category='error')
            return redirect(request.referrer)
        except werkzeug.exceptions.RequestEntityTooLarge:
            flash('The added file is too large. It should be < 1MB.',
                  category='error')
            return redirect(request.referrer)
    else:
        return render_template('update_drink.html', title='Update drink',
                               drink=drink, techniques=Drink.TECHNIQUES,
                               categories=Drink.CATEGORIES, units=Drink.UNITS,
                               ingredients=old_ingr,
                               ingr_number=ingr_number)


@drink_bp.route('/v1/drink/<drink_id>/delete_image', methods=['GET'])
@login_required
def delete_drink_pic(drink_id):
    """Delete drink's image

    GET: Delete Drink image from S3 bucket and substitute Drink image property
         to default image and redirects to 'update_drink.html' template.
    Only logged in users can use this route.

    Parameters
    ---------
    drink_id: int
    """
    drink = DrinkDbInter().get_drink(drink_id)
    ImgInter().delete_img(drink)
    return redirect(url_for('drink_bp.update_drink', drink_id=drink_id))

app/blueprints/login_bp.py
from app import lm
from app.interactors.validators import Validators
from app.interactors.web_inter import WebInter
from app.models import User

from flask import Blueprint, flash, redirect, render_template, request, url_for

from flask_login import login_required, login_user, logout_user

from werkzeug.urls import url_parse


login_bp = Blueprint('login_bp', __name__)


@lm.user_loader
def load_user(user_id):
    """User load manager.

    Paramters
    ---------
    user_id: int

    Returns
    -------
    User
        User object with user_id equal user_id.
    """
    return User.query.get(user_id)


@login_bp.route('/v1/login', methods=['GET', 'POST'])
def login():
    """Login user.

    GET: Renders template 'login.html' allowing to introduce user's login data.

    POST: Gets and verify login data introduced by user. If they are correct
          flash confirmation, login the user and redirect to home page. If
          there is any issue display the error and redirect to login page.
    """
    if request.method == 'GET':
        return render_template('login.html', title='Login')
    else:
        d = WebInter().get_form_data('email', 'password', 'remember')
        v = Validators().validate_login_data(d['email'], d['password'])
        if isinstance(v, User):
            login_user(v, remember=d['remember'])
            flash('You have been logged in.', category='success')
            next_page = request.args.get('next')
            if not next_page or url_parse(next_page).netloc != '':
                return redirect(url_for('home_bp.index'))
            return redirect(url_for('home_bp.index'))
        else:
            flash(v, category='error')
            return redirect(url_for('login_bp.login'))


@login_required
@login_bp.route('/v1/logout', methods=['GET'])
def logout():
    """Logout user.

    GET: Log out currently logged in user, flash confirmation and redirect to
         home page.
    Only logged in users can use this route.
    """
    logout_user()
    flash('You have been logged out.', category='success')
    return redirect(url_for('home_bp.index'))

app/blueprints/search_bp.py
from app.db_interactors.drink_db_inter import DrinkDbInter
from app.db_interactors.search_db_inter import SearchDbInter
from app.interactors.web_inter import WebInter
from app.models import Drink

from flask import Blueprint, redirect, render_template, request, url_for

search_bp = Blueprint('search_bp', __name__)


@search_bp.route('/v1/search', methods=['GET', 'POST'])
def search_drinks():
    """Search drinks.

    GET: Renders template 'search.html' allowing to type searching text.
    POST: Get search criteria and search text and pass it to display results
          routes.
    """
    if request.method == 'GET':
        return render_template('search.html', title='Search',
                               search_criteria=Drink.SEARCH_CRITERIA)
    else:
        search = WebInter().get_form_data('search')['search']
        criteria = WebInter().get_form_data('criteria')['criteria']
        return redirect(url_for('search_bp.display_results', search=search,
                                criteria=criteria, page=1))


@search_bp.route('/v1/results/<criteria>/<search>/<int:page>', methods=['GET'])
def display_results(search, criteria, page):
    """Display search results.

    GET: Renders 'search_results.html' template displaying drinks meeting
         search criteria.

    Parameters
    ----------
    search: String
        Search text introduced by user
    criteria: String
        Search criteria chosen by user - it can be 'drink_name' or 'ingredient'
    page: int
    """
    if criteria == 'drink_name':
        drinks = SearchDbInter().get_drinks_by_name(search, int(page))
    else:
        drinks = SearchDbInter().get_drinks_by_ingredient(search, int(page))
    msg = 'Search results for: "{}"'.format(search)
    if len(drinks.items) == 0:
        msg = 'There are no search results for: "{}"'.format(search)
    return render_template('search_results.html', title='Search results',
                           drinks=drinks, msg=msg, search=search,
                           criteria=criteria)


@search_bp.route('/v1/drinks/<category>/<int:page>', methods=['GET'])
def display_category(category, page):
    """Display category

    GET: Renders 'category.html' template displaying drinks in passed category.

    Parameters
    ----------
    category: String
        Name of category. It can takes values: all or any value in CATEGORY
        list in Drink model.
    page: int
    """
    category = category.replace('_', '/')
    if category == 'all':
        drinks = DrinkDbInter().get_all_drinks(page)
    else:
        drinks = SearchDbInter().search_by_category(category, page)
    msg = '{} Drinks:'.format(category.capitalize())
    title = category.capitalize() + ' Drinks'
    if len(drinks.items) == 0:
        msg = 'There are no drinks in {} category.'.format(category)
    return render_template('category.html', title=title, drinks=drinks,
                           msg=msg, category=category)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>{{ title }}</title>
        <meta name="description" content="The world's best website allowing searching
                                          and adding cocktails receipts. You will
                                          find here both classic drinks and original
                                          recipes." />
        <meta name="keywords" content="drinks, cocktails, whisky, rum, gin" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <link rel="stylesheet" type="text/css" href="/static/style.css" />
        <link rel="stylesheet" type="text/css" href="/static/icons/bar_p.css" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;700&display=swap" rel="stylesheet" />
    </head>
    <body>
        {% if current_user.is_authenticated and current_user.nick == None %}
                <input type="hidden" id="current-user-nick" value="{{ current_user.nick }}">
                <script type="text/javascript" src="{{ url_for('static', filename='js/set_nick.js') }}"></script>
                <div id="set-nick-window" class="form-container">
                    <h3>Please set your nick.</h3>
                    <form action="{{ url_for('facebook.set_nick') }}" method="POST">
                        <input type="text" id="nick" name="nick" placeholder="Your Nick" class="text-fields">
                        <button type="submit" name="submit" class="submit-button" onClick="PopUp('hide')">Set Nick</button>
                    </form>
                </div>
        {% endif %}
        <div id="background-content">
            <header>
                    <div id="logo">
                        <a href="/">
                            🍸 Cocktail World
                        </a>
                    </div>
                    <nav id="topnav">
                        {% if current_user.is_anonymous %}
                            <ul>
                                <li><a href="{{ url_for('search_bp.search_drinks') }}">Search</a></li>
                                <li>
                                    <a href="">Categories</a>
                                    <ol class="dropdown-menu">
                                        <li><a href="{{ url_for('search_bp.display_category', category='all', page=1) }}">All Drinks</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='whisky_bourbon', page=1) }}">Whisky/Bourbon</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='tequila_mezcal', page=1) }}">Tequila/Mezcal</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='vodka', page=1) }}">Vodka</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='rum', page=1) }}">Rum</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='gin', page=1) }}">Gin</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='other', page=1) }}">Other</a></li>
                                    </ol>
                                </li>
                                <li><a href="{{ url_for('register_bp.register_user') }}">Register</a></li>
                                <li><a href="{{ url_for('login_bp.login') }}">Login</a></li>
                            </ul>
                        {% else %}
                            <ul>
                                <li><a href="{{ url_for('search_bp.search_drinks') }}">Search</a></li>
                                <li>
                                    <a href="">Categories</a>
                                    <ol class="dropdown-menu">
                                        <li><a href="{{ url_for('search_bp.display_category', category='all', page=1) }}">All Drinks</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='whisky_bourbon', page=1) }}">Whisky/Bourbon</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='tequila_mezcal', page=1) }}">Tequila/Mezcal</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='vodka', page=1) }}">Vodka</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='rum', page=1) }}">Rum</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='gin', page=1) }}">Gin</a></li>
                                        <li><a href="{{ url_for('search_bp.display_category', category='other', page=1) }}">Other</a></li>
                                    </ol>
                                </li>
                                <li><a href="{{ url_for('drink_bp.add_drink') }}">Add Drink</a></li>
                                <li>
                                    <a href="">Manage Profile</a>
                                    <ol class="dropdown-menu">
                                        <li><a href="{{ url_for('profile_bp.display_profile', user_id=current_user.user_id, page=1) }}">Your Profile</a></li>
                                        <li><a href="{{ url_for('drink_bp.user_drinks', user_id=current_user.user_id, page=1) }}">Your Drinks</a></li>
                                        <li><a href="{{ url_for('profile_bp.update_profile_pic', user_id=current_user.user_id) }}">Change Avatar</a></li>
                                        {% if current_user.oauth_user == False %}
                                            <li><a href="{{ url_for('profile_bp.change_password') }}">Change Password</a></li>
                                        {% endif %}
                                        <li><a href="{{ url_for('profile_bp.delete_account', user_id=current_user.user_id) }}">Delete Account</a></li>
                                    </ol>
                                </li>
                                <li><a href="{{ url_for('login_bp.logout') }}">Logout</a></li>
                            </ul>
                        {% endif %}
                </nav>
            </header>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div id="flash-msg" class="{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <main>
                <div class="sidebar">
                    <div id="top-rated" class="recommended">
                        <span>Top Rated</span>
                        <a id="top-rated-link" class="sidelink">
                            <img id="top-rated-img" src="">
                            <span id="top-rated-name" class="recommended-name">Drink Name</span>
                        </a>
                    </div>
                </div>
                <div id="content">

                    {% block content %} {% endblock %}

                </div>
                <div class="sidebar">
                    <div id="most-viewed" class="recommended">
                        <span class="recommended-header">Most Viewed</span>
                        <a id="most-viewed-link" class="sidelink">
                            <img id="most-viewed-img" src="">
                            <span id="most-viewed-name" class="recommended-name">Drink Name</span>
                        </a>
                    </div>
                </div>
                <div style="clear:both;"></div>
            </main>
            <footer>
                All rights reserved &copy 2020.
            </footer>
        </div>
    <script type="text/javascript" src="{{ url_for('static', filename='js/sticky_menu.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/flashing_msg.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/display_recommended.js') }}"></script>
    </body>
</html>

app/templates/drink.html
{% extends 'base.html' %}
{% block content %}

{% endblock content %}

app/templates/drink_page.html
{% extends 'base.html' %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/voting_system.js') }}"></script>
{% endblock %}

{% block content %}
    {% with drink=drink, ingredients=ingredients, comments=comments, img=img, author=author %}
        <input type="hidden" id="drink_id" value="{{ drink.drink_id }}">
        <input type="hidden" id="user_id" value="{{ current_user.user_id }}">

        <div id="drink-page-top">
            <div id="drink-img">
                <img src="{{ drink.image }}">
            </div>
            <div id="voting-container">
                <div id="stars">
                    <div id="star1" class="star"><i class="icon-star-empty"></i></div>
                    <div id="star2" class="star"><i class="icon-star-empty"></i></div>
                    <div id="star3" class="star"><i class="icon-star-empty"></i></div>
                    <div id="star4" class="star"><i class="icon-star-empty"></i></div>
                    <div id="star5" class="star"><i class="icon-star-empty"></i></div>
                </div>
            </div>
            <span id="rate">Rate: 0 (0 votes)</span>
            <div id="drink-name-display">
                <h4> {{ drink.name.capitalize() }} </h4>
            </div>
            <div id="date-added">
                Added on {{ drink.add_date }}
            </div>
            <div id="drink-author">
                <span class="drink-attribute">Author:</span>
                <a href="{{ url_for('profile_bp.display_profile', user_id=drink.author, page=1) }}" class="author-link">
                    {{ author }}
                </a>
            </div>
            <div id="category">
                <span class="drink-attribute">Category:</span>
                {{ drink.category }}
            </div>
            <div id="technique">
                <span class="drink-attribute">Technique:</span>
                {{ drink.technique }}
            </div>
            <div id="drink-ingredients">
                <span class="drink-attribute">Ingredients:</span>
                <ul>
                    {% for i in ingredients %}
                        {% if i != None %}
                                <li>
                                    {{ i.ingr_name.capitalize() }}: {{ i.ingr_amount }} {{ i.ingr_unit }}
                                </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div style="clear: both;"></div>
        <div id="drink-mid-page">
            {% if drink.description %}
                <h6 class="drink-page-headers">Description</h6>
                <div class="drink-long-text">
                    {{ drink.description }}
                </div>
            {% endif %}
            <h6 class="drink-page-headers">Preparation</h6>
            <div class="drink-long-text">
                {{ drink.preparation }}
            </div>
        </div>
        <h6 class="drink-page-headers">Comments</h6>
        <div id="comment-section">
            {% if current_user.is_authenticated %}
                    <div id="add-comment">
                        <form action="{{ url_for('comment_bp.add_comment', drink_id=drink.drink_id) }}" method="POST">
                            <div id="textarea-div">
                                <textarea id="comment-area" name="content" maxlength="250" placeholder="Max 250 characters"></textarea>
                            </div>
                            <div id="add-button-div">
                                <button id="add-comment-button" type="submit" name="submit" class="submit-button">Send</button>
                            </div>
                            <div style="clear:both;"></div>
                        </form>
                    </div>
            {% endif %}
            <div id="all-comments">

                {% for c in comments %}
                    <div id="comment">
                        <div class="comment-header">
                            <div class="comment-author">
                                <a href="{{ url_for('profile_bp.display_profile', user_id=c.author, page=1) }}" class="author-link">
                                {{ c.author_nick }}
                                </a>
                            </div>
                            <div class="comment-operations">
                                {% if c.author == current_user.user_id %}
                                    <a href="{{ url_for('comment_bp.edit_comment', drink_id=drink.drink_id, comment_id=c.comment_id) }}" class="comment-option">
                                        Edit Comment
                                    </a>
                                    <a href="{{ url_for('comment_bp.delete_comment', drink_id=drink.drink_id, comment_id=c.comment_id) }}" class="comment-option">
                                        Delete Comment
                                    </a>
                                {% endif %}
                            </div>
                            <div class="comment-date">{{ c.date }}</div>
                            <div style="clear: both;"></div>
                        </div>
                        <div id="comment-content-display">
                            <div id="comment-text">{{ c.content }}</div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='js/voting_system.js') }}"></script>
    {% endwith %}
{% endblock content %}